/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AccessRoleEnum.
* @enum {}
* @readonly
*/
export default class AccessRoleEnum {
    
        /**
         * value: "SUPER_ADMIN"
         * @const
         */
        "SUPER_ADMIN" = "SUPER_ADMIN";

    
        /**
         * value: "ADMIN"
         * @const
         */
        "ADMIN" = "ADMIN";

    
        /**
         * value: "TEAM_MEMBER"
         * @const
         */
        "TEAM_MEMBER" = "TEAM_MEMBER";

    
        /**
         * value: "LIMITED_TEAM_MEMBER"
         * @const
         */
        "LIMITED_TEAM_MEMBER" = "LIMITED_TEAM_MEMBER";

    
        /**
         * value: "INTERVIEWER"
         * @const
         */
        "INTERVIEWER" = "INTERVIEWER";

    

    /**
    * Returns a <code>AccessRoleEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AccessRoleEnum} The enum <code>AccessRoleEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

