/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOffice model module.
 * @module model/CreateOffice
 * @version 1.0
 */
class CreateOffice {
    /**
     * Constructs a new <code>CreateOffice</code>.
     * # The Office Object ### Description The &#x60;Office&#x60; object is used to represent an office within a company.
     * @alias module:model/CreateOffice
     */
    constructor() { 
        
        CreateOffice.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateOffice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOffice} obj Optional instance to populate.
     * @return {module:model/CreateOffice} The populated <code>CreateOffice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOffice();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The office's name.
 * @member {String} name
 */
CreateOffice.prototype['name'] = undefined;

/**
 * The office's location.
 * @member {String} location
 */
CreateOffice.prototype['location'] = undefined;






export default CreateOffice;

