/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status757Enum from './Status757Enum';

/**
 * The CreateJob model module.
 * @module model/CreateJob
 * @version 1.0
 */
class CreateJob {
    /**
     * Constructs a new <code>CreateJob</code>.
     * # The Job Object ### Description The &#x60;Job&#x60; object is used to represent a Location offering at a company.
     * @alias module:model/CreateJob
     */
    constructor() { 
        
        CreateJob.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateJob</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateJob} obj Optional instance to populate.
     * @return {module:model/CreateJob} The populated <code>CreateJob</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateJob();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], Status757Enum);
            }
            if (data.hasOwnProperty('confidential')) {
                obj['confidential'] = ApiClient.convertToType(data['confidential'], 'Boolean');
            }
            if (data.hasOwnProperty('departments')) {
                obj['departments'] = ApiClient.convertToType(data['departments'], ['String']);
            }
            if (data.hasOwnProperty('offices')) {
                obj['offices'] = ApiClient.convertToType(data['offices'], ['String']);
            }
            if (data.hasOwnProperty('hiring_managers')) {
                obj['hiring_managers'] = ApiClient.convertToType(data['hiring_managers'], ['String']);
            }
            if (data.hasOwnProperty('remote_user_id')) {
                obj['remote_user_id'] = ApiClient.convertToType(data['remote_user_id'], 'String');
            }
            if (data.hasOwnProperty('number_of_openings')) {
                obj['number_of_openings'] = ApiClient.convertToType(data['number_of_openings'], 'Number');
            }
            if (data.hasOwnProperty('template_job_id')) {
                obj['template_job_id'] = ApiClient.convertToType(data['template_job_id'], 'String');
            }
            if (data.hasOwnProperty('team_name')) {
                obj['team_name'] = ApiClient.convertToType(data['team_name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
            if (data.hasOwnProperty('workflow_id')) {
                obj['workflow_id'] = ApiClient.convertToType(data['workflow_id'], 'String');
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], 'String');
            }
            if (data.hasOwnProperty('postal_code')) {
                obj['postal_code'] = ApiClient.convertToType(data['postal_code'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state_code')) {
                obj['state_code'] = ApiClient.convertToType(data['state_code'], 'String');
            }
            if (data.hasOwnProperty('country_code')) {
                obj['country_code'] = ApiClient.convertToType(data['country_code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The job's name.
 * @member {String} name
 */
CreateJob.prototype['name'] = undefined;

/**
 * The job's description.
 * @member {String} description
 */
CreateJob.prototype['description'] = undefined;

/**
 * The job's status.
 * @member {module:model/Status757Enum} status
 */
CreateJob.prototype['status'] = undefined;

/**
 * Whether the job is confidential.
 * @member {Boolean} confidential
 */
CreateJob.prototype['confidential'] = undefined;

/**
 * @member {Array.<String>} departments
 */
CreateJob.prototype['departments'] = undefined;

/**
 * @member {Array.<String>} offices
 */
CreateJob.prototype['offices'] = undefined;

/**
 * @member {Array.<String>} hiring_managers
 */
CreateJob.prototype['hiring_managers'] = undefined;

/**
 * @member {String} remote_user_id
 */
CreateJob.prototype['remote_user_id'] = undefined;

/**
 * @member {Number} number_of_openings
 */
CreateJob.prototype['number_of_openings'] = undefined;

/**
 * @member {String} template_job_id
 */
CreateJob.prototype['template_job_id'] = undefined;

/**
 * @member {String} team_name
 */
CreateJob.prototype['team_name'] = undefined;

/**
 * @member {String} type
 */
CreateJob.prototype['type'] = undefined;

/**
 * @member {String} company_id
 */
CreateJob.prototype['company_id'] = undefined;

/**
 * @member {String} workflow_id
 */
CreateJob.prototype['workflow_id'] = undefined;

/**
 * @member {String} requirements
 */
CreateJob.prototype['requirements'] = undefined;

/**
 * @member {String} postal_code
 */
CreateJob.prototype['postal_code'] = undefined;

/**
 * @member {String} city
 */
CreateJob.prototype['city'] = undefined;

/**
 * @member {String} state_code
 */
CreateJob.prototype['state_code'] = undefined;

/**
 * @member {String} country_code
 */
CreateJob.prototype['country_code'] = undefined;






export default CreateJob;

