/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmailAddress from './EmailAddress';
import PhoneNumber from './PhoneNumber';
import Url from './Url';

/**
 * The CreateCandidate model module.
 * @module model/CreateCandidate
 * @version 1.0
 */
class CreateCandidate {
    /**
     * Constructs a new <code>CreateCandidate</code>.
     * # The Candidate Object ### Description The &#x60;Candidate&#x60; object is used to represent a Candidate for various positions.
     * @alias module:model/CreateCandidate
     */
    constructor() { 
        
        CreateCandidate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateCandidate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCandidate} obj Optional instance to populate.
     * @return {module:model/CreateCandidate} The populated <code>CreateCandidate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCandidate();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('company')) {
                obj['company'] = ApiClient.convertToType(data['company'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('last_interaction_at')) {
                obj['last_interaction_at'] = ApiClient.convertToType(data['last_interaction_at'], 'Date');
            }
            if (data.hasOwnProperty('is_private')) {
                obj['is_private'] = ApiClient.convertToType(data['is_private'], 'Boolean');
            }
            if (data.hasOwnProperty('can_email')) {
                obj['can_email'] = ApiClient.convertToType(data['can_email'], 'Boolean');
            }
            if (data.hasOwnProperty('locations')) {
                obj['locations'] = ApiClient.convertToType(data['locations'], ['String']);
            }
            if (data.hasOwnProperty('phone_numbers')) {
                obj['phone_numbers'] = ApiClient.convertToType(data['phone_numbers'], [PhoneNumber]);
            }
            if (data.hasOwnProperty('email_addresses')) {
                obj['email_addresses'] = ApiClient.convertToType(data['email_addresses'], [EmailAddress]);
            }
            if (data.hasOwnProperty('urls')) {
                obj['urls'] = ApiClient.convertToType(data['urls'], [Url]);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('applications')) {
                obj['applications'] = ApiClient.convertToType(data['applications'], ['String']);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], ['String']);
            }
            if (data.hasOwnProperty('remote_user_id')) {
                obj['remote_user_id'] = ApiClient.convertToType(data['remote_user_id'], 'String');
            }
            if (data.hasOwnProperty('job_id')) {
                obj['job_id'] = ApiClient.convertToType(data['job_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The user's first name.
 * @member {String} first_name
 */
CreateCandidate.prototype['first_name'] = undefined;

/**
 * The user's last name.
 * @member {String} last_name
 */
CreateCandidate.prototype['last_name'] = undefined;

/**
 * The candidate's current company.
 * @member {String} company
 */
CreateCandidate.prototype['company'] = undefined;

/**
 * The candidate's current title.
 * @member {String} title
 */
CreateCandidate.prototype['title'] = undefined;

/**
 * When the most recent candidate interaction occurred.
 * @member {Date} last_interaction_at
 */
CreateCandidate.prototype['last_interaction_at'] = undefined;

/**
 * Whether or not the candidate is private.
 * @member {Boolean} is_private
 */
CreateCandidate.prototype['is_private'] = undefined;

/**
 * Whether or not the candidate can be emailed.
 * @member {Boolean} can_email
 */
CreateCandidate.prototype['can_email'] = undefined;

/**
 * The candidate's locations.
 * @member {Array.<String>} locations
 */
CreateCandidate.prototype['locations'] = undefined;

/**
 * @member {Array.<module:model/PhoneNumber>} phone_numbers
 */
CreateCandidate.prototype['phone_numbers'] = undefined;

/**
 * @member {Array.<module:model/EmailAddress>} email_addresses
 */
CreateCandidate.prototype['email_addresses'] = undefined;

/**
 * @member {Array.<module:model/Url>} urls
 */
CreateCandidate.prototype['urls'] = undefined;

/**
 * @member {Array.<String>} tags
 */
CreateCandidate.prototype['tags'] = undefined;

/**
 * @member {Array.<String>} applications
 */
CreateCandidate.prototype['applications'] = undefined;

/**
 * @member {Array.<String>} attachments
 */
CreateCandidate.prototype['attachments'] = undefined;

/**
 * @member {String} remote_user_id
 */
CreateCandidate.prototype['remote_user_id'] = undefined;

/**
 * @member {String} job_id
 */
CreateCandidate.prototype['job_id'] = undefined;






export default CreateCandidate;

