/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Status007Enum from './Status007Enum';

/**
 * The CreateScheduledInterview model module.
 * @module model/CreateScheduledInterview
 * @version 1.0
 */
class CreateScheduledInterview {
    /**
     * Constructs a new <code>CreateScheduledInterview</code>.
     * # The ScheduledInterview Object ### Description The &#x60;ScheduledInterview&#x60; object is used to represent an interview
     * @alias module:model/CreateScheduledInterview
     */
    constructor() { 
        
        CreateScheduledInterview.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateScheduledInterview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateScheduledInterview} obj Optional instance to populate.
     * @return {module:model/CreateScheduledInterview} The populated <code>CreateScheduledInterview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateScheduledInterview();

            if (data.hasOwnProperty('application')) {
                obj['application'] = ApiClient.convertToType(data['application'], 'String');
            }
            if (data.hasOwnProperty('job_interview_stage')) {
                obj['job_interview_stage'] = ApiClient.convertToType(data['job_interview_stage'], 'String');
            }
            if (data.hasOwnProperty('organizer')) {
                obj['organizer'] = ApiClient.convertToType(data['organizer'], 'String');
            }
            if (data.hasOwnProperty('interviewers')) {
                obj['interviewers'] = ApiClient.convertToType(data['interviewers'], ['String']);
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('start_at')) {
                obj['start_at'] = ApiClient.convertToType(data['start_at'], 'Date');
            }
            if (data.hasOwnProperty('end_at')) {
                obj['end_at'] = ApiClient.convertToType(data['end_at'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], Status007Enum);
            }
            if (data.hasOwnProperty('remote_user_id')) {
                obj['remote_user_id'] = ApiClient.convertToType(data['remote_user_id'], 'String');
            }
            if (data.hasOwnProperty('panel_id')) {
                obj['panel_id'] = ApiClient.convertToType(data['panel_id'], 'String');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The application being interviewed.
 * @member {String} application
 */
CreateScheduledInterview.prototype['application'] = undefined;

/**
 * The stage of the interview.
 * @member {String} job_interview_stage
 */
CreateScheduledInterview.prototype['job_interview_stage'] = undefined;

/**
 * The user organizing the interview.
 * @member {String} organizer
 */
CreateScheduledInterview.prototype['organizer'] = undefined;

/**
 * @member {Array.<String>} interviewers
 */
CreateScheduledInterview.prototype['interviewers'] = undefined;

/**
 * The interview's location.
 * @member {String} location
 */
CreateScheduledInterview.prototype['location'] = undefined;

/**
 * When the interview was started.
 * @member {Date} start_at
 */
CreateScheduledInterview.prototype['start_at'] = undefined;

/**
 * When the interview was ended.
 * @member {Date} end_at
 */
CreateScheduledInterview.prototype['end_at'] = undefined;

/**
 * The interview's status.
 * @member {module:model/Status007Enum} status
 */
CreateScheduledInterview.prototype['status'] = undefined;

/**
 * @member {String} remote_user_id
 */
CreateScheduledInterview.prototype['remote_user_id'] = undefined;

/**
 * @member {String} panel_id
 */
CreateScheduledInterview.prototype['panel_id'] = undefined;

/**
 * @member {String} company_id
 */
CreateScheduledInterview.prototype['company_id'] = undefined;






export default CreateScheduledInterview;

