/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatusA9fEnum from './StatusA9fEnum';

/**
 * The CreateOffer model module.
 * @module model/CreateOffer
 * @version 1.0
 */
class CreateOffer {
    /**
     * Constructs a new <code>CreateOffer</code>.
     * # The Offer Object ### Description The &#x60;Offer&#x60; object is used to represent an offer for an application.
     * @alias module:model/CreateOffer
     */
    constructor() { 
        
        CreateOffer.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateOffer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOffer} obj Optional instance to populate.
     * @return {module:model/CreateOffer} The populated <code>CreateOffer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOffer();

            if (data.hasOwnProperty('application')) {
                obj['application'] = ApiClient.convertToType(data['application'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], 'String');
            }
            if (data.hasOwnProperty('closed_at')) {
                obj['closed_at'] = ApiClient.convertToType(data['closed_at'], 'Date');
            }
            if (data.hasOwnProperty('sent_at')) {
                obj['sent_at'] = ApiClient.convertToType(data['sent_at'], 'Date');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], StatusA9fEnum);
            }
        }
        return obj;
    }


}

/**
 * The application being for the offer.
 * @member {String} application
 */
CreateOffer.prototype['application'] = undefined;

/**
 * The user who created the offer.
 * @member {String} creator
 */
CreateOffer.prototype['creator'] = undefined;

/**
 * When the offer was closed.
 * @member {Date} closed_at
 */
CreateOffer.prototype['closed_at'] = undefined;

/**
 * When the offer was sent.
 * @member {Date} sent_at
 */
CreateOffer.prototype['sent_at'] = undefined;

/**
 * The offered start date.
 * @member {Date} start_date
 */
CreateOffer.prototype['start_date'] = undefined;

/**
 * The offer's status.
 * @member {module:model/StatusA9fEnum} status
 */
CreateOffer.prototype['status'] = undefined;






export default CreateOffer;

