/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateDepartment model module.
 * @module model/CreateDepartment
 * @version 1.0
 */
class CreateDepartment {
    /**
     * Constructs a new <code>CreateDepartment</code>.
     * # The Department Object ### Description The &#x60;Department&#x60; object is used to represent a department within a company.
     * @alias module:model/CreateDepartment
     */
    constructor() { 
        
        CreateDepartment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateDepartment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDepartment} obj Optional instance to populate.
     * @return {module:model/CreateDepartment} The populated <code>CreateDepartment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDepartment();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The department's name.
 * @member {String} name
 */
CreateDepartment.prototype['name'] = undefined;






export default CreateDepartment;

