/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DisabilityStatusEnum.
* @enum {}
* @readonly
*/
export default class DisabilityStatusEnum {
    
        /**
         * value: "YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY"
         * @const
         */
        "YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY" = "YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY";

    
        /**
         * value: "NO_I_DONT_HAVE_A_DISABILITY"
         * @const
         */
        "NO_I_DONT_HAVE_A_DISABILITY" = "NO_I_DONT_HAVE_A_DISABILITY";

    
        /**
         * value: "I_DONT_WISH_TO_ANSWER"
         * @const
         */
        "I_DONT_WISH_TO_ANSWER" = "I_DONT_WISH_TO_ANSWER";

    

    /**
    * Returns a <code>DisabilityStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DisabilityStatusEnum} The enum <code>DisabilityStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

