/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DisabilityStatusEnum from './DisabilityStatusEnum';
import GenderEnum from './GenderEnum';
import RaceEnum from './RaceEnum';
import RemoteData from './RemoteData';
import VeteranStatusEnum from './VeteranStatusEnum';

/**
 * The EEOC model module.
 * @module model/EEOC
 * @version 1.0
 */
class EEOC {
    /**
     * Constructs a new <code>EEOC</code>.
     * # The EEOC Object ### Description The &#x60;EEOC&#x60; object is used to represent the Equal Employment Opportunity Commission information for a candidate.  ### Usage Example Fetch from the &#x60;LIST EEOCs&#x60; endpoint and filter by &#x60;candidate&#x60; to show all EEOC information for a candidate.
     * @alias module:model/EEOC
     */
    constructor() { 
        
        EEOC.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EEOC</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EEOC} obj Optional instance to populate.
     * @return {module:model/EEOC} The populated <code>EEOC</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EEOC();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('candidate')) {
                obj['candidate'] = ApiClient.convertToType(data['candidate'], 'String');
            }
            if (data.hasOwnProperty('submitted_at')) {
                obj['submitted_at'] = ApiClient.convertToType(data['submitted_at'], 'Date');
            }
            if (data.hasOwnProperty('race')) {
                obj['race'] = ApiClient.convertToType(data['race'], RaceEnum);
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], GenderEnum);
            }
            if (data.hasOwnProperty('veteran_status')) {
                obj['veteran_status'] = ApiClient.convertToType(data['veteran_status'], VeteranStatusEnum);
            }
            if (data.hasOwnProperty('disability_status')) {
                obj['disability_status'] = ApiClient.convertToType(data['disability_status'], DisabilityStatusEnum);
            }
            if (data.hasOwnProperty('remote_data')) {
                obj['remote_data'] = ApiClient.convertToType(data['remote_data'], [RemoteData]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
EEOC.prototype['id'] = undefined;

/**
 * The third-party API ID of the matching object.
 * @member {String} remote_id
 */
EEOC.prototype['remote_id'] = undefined;

/**
 * The candidate being represented.
 * @member {String} candidate
 */
EEOC.prototype['candidate'] = undefined;

/**
 * When the information was submitted.
 * @member {Date} submitted_at
 */
EEOC.prototype['submitted_at'] = undefined;

/**
 * The candidate's race.
 * @member {module:model/RaceEnum} race
 */
EEOC.prototype['race'] = undefined;

/**
 * The candidate's gender.
 * @member {module:model/GenderEnum} gender
 */
EEOC.prototype['gender'] = undefined;

/**
 * The candidate's veteran status.
 * @member {module:model/VeteranStatusEnum} veteran_status
 */
EEOC.prototype['veteran_status'] = undefined;

/**
 * The candidate's disability status.
 * @member {module:model/DisabilityStatusEnum} disability_status
 */
EEOC.prototype['disability_status'] = undefined;

/**
 * @member {Array.<module:model/RemoteData>} remote_data
 */
EEOC.prototype['remote_data'] = undefined;






export default EEOC;

