/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OverallRecommendationEnum.
* @enum {}
* @readonly
*/
export default class OverallRecommendationEnum {
    
        /**
         * value: "DEFINITELY_NO"
         * @const
         */
        "DEFINITELY_NO" = "DEFINITELY_NO";

    
        /**
         * value: "NO"
         * @const
         */
        "NO" = "NO";

    
        /**
         * value: "YES"
         * @const
         */
        "YES" = "YES";

    
        /**
         * value: "STRONG_YES"
         * @const
         */
        "STRONG_YES" = "STRONG_YES";

    
        /**
         * value: "NO_DECISION"
         * @const
         */
        "NO_DECISION" = "NO_DECISION";

    

    /**
    * Returns a <code>OverallRecommendationEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OverallRecommendationEnum} The enum <code>OverallRecommendationEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

