/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobInterviewStage from './JobInterviewStage';

/**
 * The PaginatedJobInterviewStageList model module.
 * @module model/PaginatedJobInterviewStageList
 * @version 1.0
 */
class PaginatedJobInterviewStageList {
    /**
     * Constructs a new <code>PaginatedJobInterviewStageList</code>.
     * @alias module:model/PaginatedJobInterviewStageList
     */
    constructor() { 
        
        PaginatedJobInterviewStageList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginatedJobInterviewStageList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaginatedJobInterviewStageList} obj Optional instance to populate.
     * @return {module:model/PaginatedJobInterviewStageList} The populated <code>PaginatedJobInterviewStageList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginatedJobInterviewStageList();

            if (data.hasOwnProperty('next')) {
                obj['next'] = ApiClient.convertToType(data['next'], 'String');
            }
            if (data.hasOwnProperty('previous')) {
                obj['previous'] = ApiClient.convertToType(data['previous'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [JobInterviewStage]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} next
 */
PaginatedJobInterviewStageList.prototype['next'] = undefined;

/**
 * @member {String} previous
 */
PaginatedJobInterviewStageList.prototype['previous'] = undefined;

/**
 * @member {Array.<module:model/JobInterviewStage>} results
 */
PaginatedJobInterviewStageList.prototype['results'] = undefined;






export default PaginatedJobInterviewStageList;

