/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PhoneNumberTypeEnum from './PhoneNumberTypeEnum';

/**
 * The PhoneNumber model module.
 * @module model/PhoneNumber
 * @version 1.0
 */
class PhoneNumber {
    /**
     * Constructs a new <code>PhoneNumber</code>.
     * # The PhoneNumber Object ### Description The &#x60;PhoneNumber&#x60; object is used to represent a candidate&#39;s phone number.  ### Usage Example Fetch from the &#x60;GET Candidate&#x60; endpoint and view their phone numbers.
     * @alias module:model/PhoneNumber
     */
    constructor() { 
        
        PhoneNumber.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PhoneNumber</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PhoneNumber} obj Optional instance to populate.
     * @return {module:model/PhoneNumber} The populated <code>PhoneNumber</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PhoneNumber();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('phone_number_type')) {
                obj['phone_number_type'] = ApiClient.convertToType(data['phone_number_type'], PhoneNumberTypeEnum);
            }
        }
        return obj;
    }


}

/**
 * The phone number.
 * @member {String} value
 */
PhoneNumber.prototype['value'] = undefined;

/**
 * The type of phone number.
 * @member {module:model/PhoneNumberTypeEnum} phone_number_type
 */
PhoneNumber.prototype['phone_number_type'] = undefined;






export default PhoneNumber;

