/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PhoneNumberTypeEnum.
* @enum {}
* @readonly
*/
export default class PhoneNumberTypeEnum {
    
        /**
         * value: "HOME"
         * @const
         */
        "HOME" = "HOME";

    
        /**
         * value: "WORK"
         * @const
         */
        "WORK" = "WORK";

    
        /**
         * value: "MOBILE"
         * @const
         */
        "MOBILE" = "MOBILE";

    
        /**
         * value: "SKYPE"
         * @const
         */
        "SKYPE" = "SKYPE";

    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER" = "OTHER";

    

    /**
    * Returns a <code>PhoneNumberTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PhoneNumberTypeEnum} The enum <code>PhoneNumberTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

