/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class RaceEnum.
* @enum {}
* @readonly
*/
export default class RaceEnum {
    
        /**
         * value: "AMERICAN_INDIAN_OR_ALASKAN_NATIVE"
         * @const
         */
        "AMERICAN_INDIAN_OR_ALASKAN_NATIVE" = "AMERICAN_INDIAN_OR_ALASKAN_NATIVE";

    
        /**
         * value: "ASIAN"
         * @const
         */
        "ASIAN" = "ASIAN";

    
        /**
         * value: "BLACK_OR_AFRICAN_AMERICAN"
         * @const
         */
        "BLACK_OR_AFRICAN_AMERICAN" = "BLACK_OR_AFRICAN_AMERICAN";

    
        /**
         * value: "HISPANIC_OR_LATINO"
         * @const
         */
        "HISPANIC_OR_LATINO" = "HISPANIC_OR_LATINO";

    
        /**
         * value: "WHITE"
         * @const
         */
        "WHITE" = "WHITE";

    
        /**
         * value: "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER"
         * @const
         */
        "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER" = "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER";

    
        /**
         * value: "TWO_OR_MORE_RACES"
         * @const
         */
        "TWO_OR_MORE_RACES" = "TWO_OR_MORE_RACES";

    
        /**
         * value: "DECLINE_TO_SELF_IDENTIFY"
         * @const
         */
        "DECLINE_TO_SELF_IDENTIFY" = "DECLINE_TO_SELF_IDENTIFY";

    

    /**
    * Returns a <code>RaceEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/RaceEnum} The enum <code>RaceEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

