/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OverallRecommendationEnum from './OverallRecommendationEnum';

/**
 * The ScorecardRequest model module.
 * @module model/ScorecardRequest
 * @version 1.0
 */
class ScorecardRequest {
    /**
     * Constructs a new <code>ScorecardRequest</code>.
     * # The Scorecard Object ### Description The &#x60;Scorecard&#x60; object is used to represent a Scorecard for an interview  ### Usage Example Fetch from the &#x60;LIST Scorecards&#x60; endpoint and filter by &#x60;application&#x60; to show all scorecard for an applicant.
     * @alias module:model/ScorecardRequest
     */
    constructor() { 
        
        ScorecardRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ScorecardRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ScorecardRequest} obj Optional instance to populate.
     * @return {module:model/ScorecardRequest} The populated <code>ScorecardRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ScorecardRequest();

            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('application')) {
                obj['application'] = ApiClient.convertToType(data['application'], 'String');
            }
            if (data.hasOwnProperty('interview')) {
                obj['interview'] = ApiClient.convertToType(data['interview'], 'String');
            }
            if (data.hasOwnProperty('interviewer')) {
                obj['interviewer'] = ApiClient.convertToType(data['interviewer'], 'String');
            }
            if (data.hasOwnProperty('remote_created_at')) {
                obj['remote_created_at'] = ApiClient.convertToType(data['remote_created_at'], 'Date');
            }
            if (data.hasOwnProperty('submitted_at')) {
                obj['submitted_at'] = ApiClient.convertToType(data['submitted_at'], 'Date');
            }
            if (data.hasOwnProperty('overall_recommendation')) {
                obj['overall_recommendation'] = ApiClient.convertToType(data['overall_recommendation'], OverallRecommendationEnum);
            }
        }
        return obj;
    }


}

/**
 * The third-party API ID of the matching object.
 * @member {String} remote_id
 */
ScorecardRequest.prototype['remote_id'] = undefined;

/**
 * The application being scored.
 * @member {String} application
 */
ScorecardRequest.prototype['application'] = undefined;

/**
 * The interview being scored.
 * @member {String} interview
 */
ScorecardRequest.prototype['interview'] = undefined;

/**
 * The interviewer doing the scoring.
 * @member {String} interviewer
 */
ScorecardRequest.prototype['interviewer'] = undefined;

/**
 * When the third party's scorecard was created.
 * @member {Date} remote_created_at
 */
ScorecardRequest.prototype['remote_created_at'] = undefined;

/**
 * When the scorecard was submitted.
 * @member {Date} submitted_at
 */
ScorecardRequest.prototype['submitted_at'] = undefined;

/**
 * The inteviewer's recommendation.
 * @member {module:model/OverallRecommendationEnum} overall_recommendation
 */
ScorecardRequest.prototype['overall_recommendation'] = undefined;






export default ScorecardRequest;

