/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class StatusA9fEnum.
* @enum {}
* @readonly
*/
export default class StatusA9fEnum {
    
        /**
         * value: "DRAFT"
         * @const
         */
        "DRAFT" = "DRAFT";

    
        /**
         * value: "APPROVAL-SENT"
         * @const
         */
        "APPROVAL-SENT" = "APPROVAL-SENT";

    
        /**
         * value: "APPROVED"
         * @const
         */
        "APPROVED" = "APPROVED";

    
        /**
         * value: "SENT"
         * @const
         */
        "SENT" = "SENT";

    
        /**
         * value: "SENT-MANUALLY"
         * @const
         */
        "SENT-MANUALLY" = "SENT-MANUALLY";

    
        /**
         * value: "OPENED"
         * @const
         */
        "OPENED" = "OPENED";

    
        /**
         * value: "DENIED"
         * @const
         */
        "DENIED" = "DENIED";

    
        /**
         * value: "SIGNED"
         * @const
         */
        "SIGNED" = "SIGNED";

    
        /**
         * value: "DEPRECATED"
         * @const
         */
        "DEPRECATED" = "DEPRECATED";

    

    /**
    * Returns a <code>StatusA9fEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/StatusA9fEnum} The enum <code>StatusA9fEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

