/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Status757Enum.
* @enum {}
* @readonly
*/
export default class Status757Enum {
    
        /**
         * value: "OPEN"
         * @const
         */
        "OPEN" = "OPEN";

    
        /**
         * value: "CLOSED"
         * @const
         */
        "CLOSED" = "CLOSED";

    
        /**
         * value: "DRAFT"
         * @const
         */
        "DRAFT" = "DRAFT";

    
        /**
         * value: "ARCHIVED"
         * @const
         */
        "ARCHIVED" = "ARCHIVED";

    
        /**
         * value: "PENDING"
         * @const
         */
        "PENDING" = "PENDING";

    

    /**
    * Returns a <code>Status757Enum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Status757Enum} The enum <code>Status757Enum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

