/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UrlTypeEnum from './UrlTypeEnum';

/**
 * The Url model module.
 * @module model/Url
 * @version 1.0
 */
class Url {
    /**
     * Constructs a new <code>Url</code>.
     * # The Url Object ### Description The &#x60;Url&#x60; object is used to represent a candidate&#39;s website.  ### Usage Example Fetch from the &#x60;GET Candidate&#x60; endpoint and view their website urls.
     * @alias module:model/Url
     */
    constructor() { 
        
        Url.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Url</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Url} obj Optional instance to populate.
     * @return {module:model/Url} The populated <code>Url</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Url();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('url_type')) {
                obj['url_type'] = ApiClient.convertToType(data['url_type'], UrlTypeEnum);
            }
        }
        return obj;
    }


}

/**
 * The site's url.
 * @member {String} value
 */
Url.prototype['value'] = undefined;

/**
 * The type of site.
 * @member {module:model/UrlTypeEnum} url_type
 */
Url.prototype['url_type'] = undefined;






export default Url;

