/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UrlTypeEnum.
* @enum {}
* @readonly
*/
export default class UrlTypeEnum {
    
        /**
         * value: "PERSONAL"
         * @const
         */
        "PERSONAL" = "PERSONAL";

    
        /**
         * value: "COMPANY"
         * @const
         */
        "COMPANY" = "COMPANY";

    
        /**
         * value: "PORTFOLIO"
         * @const
         */
        "PORTFOLIO" = "PORTFOLIO";

    
        /**
         * value: "BLOG"
         * @const
         */
        "BLOG" = "BLOG";

    
        /**
         * value: "SOCIAL_MEDIA"
         * @const
         */
        "SOCIAL_MEDIA" = "SOCIAL_MEDIA";

    
        /**
         * value: "OTHER"
         * @const
         */
        "OTHER" = "OTHER";

    

    /**
    * Returns a <code>UrlTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/UrlTypeEnum} The enum <code>UrlTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

