/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeAtsApi);
  }
}(this, function(expect, MergeAtsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeAtsApi.CandidateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CandidateRequest', function() {
    it('should create an instance of CandidateRequest', function() {
      // uncomment below and update the code to test CandidateRequest
      //var instane = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be.a(MergeAtsApi.CandidateRequest);
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property company (base name: "company")', function() {
      // uncomment below and update the code to test the property company
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property remoteCreatedAt (base name: "remote_created_at")', function() {
      // uncomment below and update the code to test the property remoteCreatedAt
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property remoteUpdatedAt (base name: "remote_updated_at")', function() {
      // uncomment below and update the code to test the property remoteUpdatedAt
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastInteractionAt (base name: "last_interaction_at")', function() {
      // uncomment below and update the code to test the property lastInteractionAt
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property isPrivate (base name: "is_private")', function() {
      // uncomment below and update the code to test the property isPrivate
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property canEmail (base name: "can_email")', function() {
      // uncomment below and update the code to test the property canEmail
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property locations (base name: "locations")', function() {
      // uncomment below and update the code to test the property locations
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumbers (base name: "phone_numbers")', function() {
      // uncomment below and update the code to test the property phoneNumbers
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property emailAddresses (base name: "email_addresses")', function() {
      // uncomment below and update the code to test the property emailAddresses
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property urls (base name: "urls")', function() {
      // uncomment below and update the code to test the property urls
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new MergeAtsApi.CandidateRequest();
      //expect(instance).to.be();
    });

  });

}));
