/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeAtsApi);
  }
}(this, function(expect, MergeAtsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeAtsApi.CreateJob();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateJob', function() {
    it('should create an instance of CreateJob', function() {
      // uncomment below and update the code to test CreateJob
      //var instane = new MergeAtsApi.CreateJob();
      //expect(instance).to.be.a(MergeAtsApi.CreateJob);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property confidential (base name: "confidential")', function() {
      // uncomment below and update the code to test the property confidential
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property departments (base name: "departments")', function() {
      // uncomment below and update the code to test the property departments
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property offices (base name: "offices")', function() {
      // uncomment below and update the code to test the property offices
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property hiringManagers (base name: "hiring_managers")', function() {
      // uncomment below and update the code to test the property hiringManagers
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property remoteUserId (base name: "remote_user_id")', function() {
      // uncomment below and update the code to test the property remoteUserId
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property numberOfOpenings (base name: "number_of_openings")', function() {
      // uncomment below and update the code to test the property numberOfOpenings
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property templateJobId (base name: "template_job_id")', function() {
      // uncomment below and update the code to test the property templateJobId
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property teamName (base name: "team_name")', function() {
      // uncomment below and update the code to test the property teamName
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property workflowId (base name: "workflow_id")', function() {
      // uncomment below and update the code to test the property workflowId
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property requirements (base name: "requirements")', function() {
      // uncomment below and update the code to test the property requirements
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property stateCode (base name: "state_code")', function() {
      // uncomment below and update the code to test the property stateCode
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

    it('should have the property countryCode (base name: "country_code")', function() {
      // uncomment below and update the code to test the property countryCode
      //var instance = new MergeAtsApi.CreateJob();
      //expect(instance).to.be();
    });

  });

}));
