/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeAtsApi);
  }
}(this, function(expect, MergeAtsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeAtsApi.EEOC();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EEOC', function() {
    it('should create an instance of EEOC', function() {
      // uncomment below and update the code to test EEOC
      //var instane = new MergeAtsApi.EEOC();
      //expect(instance).to.be.a(MergeAtsApi.EEOC);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property candidate (base name: "candidate")', function() {
      // uncomment below and update the code to test the property candidate
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property submittedAt (base name: "submitted_at")', function() {
      // uncomment below and update the code to test the property submittedAt
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property race (base name: "race")', function() {
      // uncomment below and update the code to test the property race
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property veteranStatus (base name: "veteran_status")', function() {
      // uncomment below and update the code to test the property veteranStatus
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property disabilityStatus (base name: "disability_status")', function() {
      // uncomment below and update the code to test the property disabilityStatus
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

    it('should have the property remoteData (base name: "remote_data")', function() {
      // uncomment below and update the code to test the property remoteData
      //var instance = new MergeAtsApi.EEOC();
      //expect(instance).to.be();
    });

  });

}));
