/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeAtsApi);
  }
}(this, function(expect, MergeAtsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeAtsApi.Job();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Job', function() {
    it('should create an instance of Job', function() {
      // uncomment below and update the code to test Job
      //var instane = new MergeAtsApi.Job();
      //expect(instance).to.be.a(MergeAtsApi.Job);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property remoteCreatedAt (base name: "remote_created_at")', function() {
      // uncomment below and update the code to test the property remoteCreatedAt
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property remoteUpdatedAt (base name: "remote_updated_at")', function() {
      // uncomment below and update the code to test the property remoteUpdatedAt
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property confidential (base name: "confidential")', function() {
      // uncomment below and update the code to test the property confidential
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property departments (base name: "departments")', function() {
      // uncomment below and update the code to test the property departments
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property offices (base name: "offices")', function() {
      // uncomment below and update the code to test the property offices
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property hiringManagers (base name: "hiring_managers")', function() {
      // uncomment below and update the code to test the property hiringManagers
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

    it('should have the property remoteData (base name: "remote_data")', function() {
      // uncomment below and update the code to test the property remoteData
      //var instance = new MergeAtsApi.Job();
      //expect(instance).to.be();
    });

  });

}));
