/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeAtsApi);
  }
}(this, function(expect, MergeAtsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeAtsApi.Offer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Offer', function() {
    it('should create an instance of Offer', function() {
      // uncomment below and update the code to test Offer
      //var instane = new MergeAtsApi.Offer();
      //expect(instance).to.be.a(MergeAtsApi.Offer);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property application (base name: "application")', function() {
      // uncomment below and update the code to test the property application
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property remoteCreatedAt (base name: "remote_created_at")', function() {
      // uncomment below and update the code to test the property remoteCreatedAt
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property closedAt (base name: "closed_at")', function() {
      // uncomment below and update the code to test the property closedAt
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property sentAt (base name: "sent_at")', function() {
      // uncomment below and update the code to test the property sentAt
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

    it('should have the property remoteData (base name: "remote_data")', function() {
      // uncomment below and update the code to test the property remoteData
      //var instance = new MergeAtsApi.Offer();
      //expect(instance).to.be();
    });

  });

}));
