/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeAtsApi);
  }
}(this, function(expect, MergeAtsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeAtsApi.ScheduledInterviewRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ScheduledInterviewRequest', function() {
    it('should create an instance of ScheduledInterviewRequest', function() {
      // uncomment below and update the code to test ScheduledInterviewRequest
      //var instane = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be.a(MergeAtsApi.ScheduledInterviewRequest);
    });

    it('should have the property remoteId (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remoteId
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property application (base name: "application")', function() {
      // uncomment below and update the code to test the property application
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property jobInterviewStage (base name: "job_interview_stage")', function() {
      // uncomment below and update the code to test the property jobInterviewStage
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property organizer (base name: "organizer")', function() {
      // uncomment below and update the code to test the property organizer
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property interviewers (base name: "interviewers")', function() {
      // uncomment below and update the code to test the property interviewers
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property startAt (base name: "start_at")', function() {
      // uncomment below and update the code to test the property startAt
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property endAt (base name: "end_at")', function() {
      // uncomment below and update the code to test the property endAt
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property remoteCreatedAt (base name: "remote_created_at")', function() {
      // uncomment below and update the code to test the property remoteCreatedAt
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property remoteUpdatedAt (base name: "remote_updated_at")', function() {
      // uncomment below and update the code to test the property remoteUpdatedAt
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MergeAtsApi.ScheduledInterviewRequest();
      //expect(instance).to.be();
    });

  });

}));
