/**
 * Merge ATS API
 * The unified API for building rich integrations with multiple Applicant Tracking System platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccessRoleEnum from './model/AccessRoleEnum';
import AccountIntegration from './model/AccountIntegration';
import AccountToken from './model/AccountToken';
import Activity from './model/Activity';
import ActivityTypeEnum from './model/ActivityTypeEnum';
import Application from './model/Application';
import Attachment from './model/Attachment';
import AvailableActions from './model/AvailableActions';
import Candidate from './model/Candidate';
import CreateActivity from './model/CreateActivity';
import CreateApplication from './model/CreateApplication';
import CreateAttachment from './model/CreateAttachment';
import CreateCandidate from './model/CreateCandidate';
import CreateDepartment from './model/CreateDepartment';
import CreateJob from './model/CreateJob';
import CreateJobInterviewStage from './model/CreateJobInterviewStage';
import CreateOffer from './model/CreateOffer';
import CreateOffice from './model/CreateOffice';
import CreateRejectReason from './model/CreateRejectReason';
import CreateRemoteUser from './model/CreateRemoteUser';
import CreateScheduledInterview from './model/CreateScheduledInterview';
import CreateScorecard from './model/CreateScorecard';
import CreateTag from './model/CreateTag';
import DataPassthrough from './model/DataPassthrough';
import Department from './model/Department';
import DisabilityStatusEnum from './model/DisabilityStatusEnum';
import EEOC from './model/EEOC';
import EmailAddress from './model/EmailAddress';
import EmailAddressTypeEnum from './model/EmailAddressTypeEnum';
import EndUserDetails from './model/EndUserDetails';
import GenderEnum from './model/GenderEnum';
import Job from './model/Job';
import JobInterviewStage from './model/JobInterviewStage';
import LinkToken from './model/LinkToken';
import MethodEnum from './model/MethodEnum';
import ModelOperation from './model/ModelOperation';
import Offer from './model/Offer';
import Office from './model/Office';
import OverallRecommendationEnum from './model/OverallRecommendationEnum';
import PaginatedActivityList from './model/PaginatedActivityList';
import PaginatedApplicationList from './model/PaginatedApplicationList';
import PaginatedAttachmentList from './model/PaginatedAttachmentList';
import PaginatedCandidateList from './model/PaginatedCandidateList';
import PaginatedDepartmentList from './model/PaginatedDepartmentList';
import PaginatedEEOCList from './model/PaginatedEEOCList';
import PaginatedJobInterviewStageList from './model/PaginatedJobInterviewStageList';
import PaginatedJobList from './model/PaginatedJobList';
import PaginatedOfferList from './model/PaginatedOfferList';
import PaginatedOfficeList from './model/PaginatedOfficeList';
import PaginatedRejectReasonList from './model/PaginatedRejectReasonList';
import PaginatedRemoteUserList from './model/PaginatedRemoteUserList';
import PaginatedScheduledInterviewList from './model/PaginatedScheduledInterviewList';
import PaginatedScorecardList from './model/PaginatedScorecardList';
import PaginatedTagList from './model/PaginatedTagList';
import PhoneNumber from './model/PhoneNumber';
import PhoneNumberTypeEnum from './model/PhoneNumberTypeEnum';
import RaceEnum from './model/RaceEnum';
import RejectReason from './model/RejectReason';
import RemoteData from './model/RemoteData';
import RemoteResponse from './model/RemoteResponse';
import RemoteUser from './model/RemoteUser';
import ScheduledInterview from './model/ScheduledInterview';
import Scorecard from './model/Scorecard';
import Status007Enum from './model/Status007Enum';
import Status757Enum from './model/Status757Enum';
import StatusA9fEnum from './model/StatusA9fEnum';
import Tag from './model/Tag';
import Url from './model/Url';
import UrlTypeEnum from './model/UrlTypeEnum';
import VeteranStatusEnum from './model/VeteranStatusEnum';
import VisibilityEnum from './model/VisibilityEnum';
import AccountTokenApi from './api/AccountTokenApi';
import ActivitiesApi from './api/ActivitiesApi';
import ApplicationsApi from './api/ApplicationsApi';
import AttachmentsApi from './api/AttachmentsApi';
import AvailableActionsApi from './api/AvailableActionsApi';
import CandidatesApi from './api/CandidatesApi';
import DepartmentsApi from './api/DepartmentsApi';
import EeocsApi from './api/EeocsApi';
import InterviewsApi from './api/InterviewsApi';
import JobInterviewStagesApi from './api/JobInterviewStagesApi';
import JobsApi from './api/JobsApi';
import LinkTokenApi from './api/LinkTokenApi';
import OffersApi from './api/OffersApi';
import OfficesApi from './api/OfficesApi';
import PassthroughApi from './api/PassthroughApi';
import RejectReasonsApi from './api/RejectReasonsApi';
import ScorecardsApi from './api/ScorecardsApi';
import TagsApi from './api/TagsApi';
import UsersApi from './api/UsersApi';


/**
* The_unified_API_for_building_rich_integrations_with_multiple_Applicant_Tracking_System_platforms_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MergeAtsApi = require('index'); // See note below*.
* var xxxSvc = new MergeAtsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MergeAtsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MergeAtsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MergeAtsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccessRoleEnum model constructor.
     * @property {module:model/AccessRoleEnum}
     */
    AccessRoleEnum,

    /**
     * The AccountIntegration model constructor.
     * @property {module:model/AccountIntegration}
     */
    AccountIntegration,

    /**
     * The AccountToken model constructor.
     * @property {module:model/AccountToken}
     */
    AccountToken,

    /**
     * The Activity model constructor.
     * @property {module:model/Activity}
     */
    Activity,

    /**
     * The ActivityTypeEnum model constructor.
     * @property {module:model/ActivityTypeEnum}
     */
    ActivityTypeEnum,

    /**
     * The Application model constructor.
     * @property {module:model/Application}
     */
    Application,

    /**
     * The Attachment model constructor.
     * @property {module:model/Attachment}
     */
    Attachment,

    /**
     * The AvailableActions model constructor.
     * @property {module:model/AvailableActions}
     */
    AvailableActions,

    /**
     * The Candidate model constructor.
     * @property {module:model/Candidate}
     */
    Candidate,

    /**
     * The CreateActivity model constructor.
     * @property {module:model/CreateActivity}
     */
    CreateActivity,

    /**
     * The CreateApplication model constructor.
     * @property {module:model/CreateApplication}
     */
    CreateApplication,

    /**
     * The CreateAttachment model constructor.
     * @property {module:model/CreateAttachment}
     */
    CreateAttachment,

    /**
     * The CreateCandidate model constructor.
     * @property {module:model/CreateCandidate}
     */
    CreateCandidate,

    /**
     * The CreateDepartment model constructor.
     * @property {module:model/CreateDepartment}
     */
    CreateDepartment,

    /**
     * The CreateJob model constructor.
     * @property {module:model/CreateJob}
     */
    CreateJob,

    /**
     * The CreateJobInterviewStage model constructor.
     * @property {module:model/CreateJobInterviewStage}
     */
    CreateJobInterviewStage,

    /**
     * The CreateOffer model constructor.
     * @property {module:model/CreateOffer}
     */
    CreateOffer,

    /**
     * The CreateOffice model constructor.
     * @property {module:model/CreateOffice}
     */
    CreateOffice,

    /**
     * The CreateRejectReason model constructor.
     * @property {module:model/CreateRejectReason}
     */
    CreateRejectReason,

    /**
     * The CreateRemoteUser model constructor.
     * @property {module:model/CreateRemoteUser}
     */
    CreateRemoteUser,

    /**
     * The CreateScheduledInterview model constructor.
     * @property {module:model/CreateScheduledInterview}
     */
    CreateScheduledInterview,

    /**
     * The CreateScorecard model constructor.
     * @property {module:model/CreateScorecard}
     */
    CreateScorecard,

    /**
     * The CreateTag model constructor.
     * @property {module:model/CreateTag}
     */
    CreateTag,

    /**
     * The DataPassthrough model constructor.
     * @property {module:model/DataPassthrough}
     */
    DataPassthrough,

    /**
     * The Department model constructor.
     * @property {module:model/Department}
     */
    Department,

    /**
     * The DisabilityStatusEnum model constructor.
     * @property {module:model/DisabilityStatusEnum}
     */
    DisabilityStatusEnum,

    /**
     * The EEOC model constructor.
     * @property {module:model/EEOC}
     */
    EEOC,

    /**
     * The EmailAddress model constructor.
     * @property {module:model/EmailAddress}
     */
    EmailAddress,

    /**
     * The EmailAddressTypeEnum model constructor.
     * @property {module:model/EmailAddressTypeEnum}
     */
    EmailAddressTypeEnum,

    /**
     * The EndUserDetails model constructor.
     * @property {module:model/EndUserDetails}
     */
    EndUserDetails,

    /**
     * The GenderEnum model constructor.
     * @property {module:model/GenderEnum}
     */
    GenderEnum,

    /**
     * The Job model constructor.
     * @property {module:model/Job}
     */
    Job,

    /**
     * The JobInterviewStage model constructor.
     * @property {module:model/JobInterviewStage}
     */
    JobInterviewStage,

    /**
     * The LinkToken model constructor.
     * @property {module:model/LinkToken}
     */
    LinkToken,

    /**
     * The MethodEnum model constructor.
     * @property {module:model/MethodEnum}
     */
    MethodEnum,

    /**
     * The ModelOperation model constructor.
     * @property {module:model/ModelOperation}
     */
    ModelOperation,

    /**
     * The Offer model constructor.
     * @property {module:model/Offer}
     */
    Offer,

    /**
     * The Office model constructor.
     * @property {module:model/Office}
     */
    Office,

    /**
     * The OverallRecommendationEnum model constructor.
     * @property {module:model/OverallRecommendationEnum}
     */
    OverallRecommendationEnum,

    /**
     * The PaginatedActivityList model constructor.
     * @property {module:model/PaginatedActivityList}
     */
    PaginatedActivityList,

    /**
     * The PaginatedApplicationList model constructor.
     * @property {module:model/PaginatedApplicationList}
     */
    PaginatedApplicationList,

    /**
     * The PaginatedAttachmentList model constructor.
     * @property {module:model/PaginatedAttachmentList}
     */
    PaginatedAttachmentList,

    /**
     * The PaginatedCandidateList model constructor.
     * @property {module:model/PaginatedCandidateList}
     */
    PaginatedCandidateList,

    /**
     * The PaginatedDepartmentList model constructor.
     * @property {module:model/PaginatedDepartmentList}
     */
    PaginatedDepartmentList,

    /**
     * The PaginatedEEOCList model constructor.
     * @property {module:model/PaginatedEEOCList}
     */
    PaginatedEEOCList,

    /**
     * The PaginatedJobInterviewStageList model constructor.
     * @property {module:model/PaginatedJobInterviewStageList}
     */
    PaginatedJobInterviewStageList,

    /**
     * The PaginatedJobList model constructor.
     * @property {module:model/PaginatedJobList}
     */
    PaginatedJobList,

    /**
     * The PaginatedOfferList model constructor.
     * @property {module:model/PaginatedOfferList}
     */
    PaginatedOfferList,

    /**
     * The PaginatedOfficeList model constructor.
     * @property {module:model/PaginatedOfficeList}
     */
    PaginatedOfficeList,

    /**
     * The PaginatedRejectReasonList model constructor.
     * @property {module:model/PaginatedRejectReasonList}
     */
    PaginatedRejectReasonList,

    /**
     * The PaginatedRemoteUserList model constructor.
     * @property {module:model/PaginatedRemoteUserList}
     */
    PaginatedRemoteUserList,

    /**
     * The PaginatedScheduledInterviewList model constructor.
     * @property {module:model/PaginatedScheduledInterviewList}
     */
    PaginatedScheduledInterviewList,

    /**
     * The PaginatedScorecardList model constructor.
     * @property {module:model/PaginatedScorecardList}
     */
    PaginatedScorecardList,

    /**
     * The PaginatedTagList model constructor.
     * @property {module:model/PaginatedTagList}
     */
    PaginatedTagList,

    /**
     * The PhoneNumber model constructor.
     * @property {module:model/PhoneNumber}
     */
    PhoneNumber,

    /**
     * The PhoneNumberTypeEnum model constructor.
     * @property {module:model/PhoneNumberTypeEnum}
     */
    PhoneNumberTypeEnum,

    /**
     * The RaceEnum model constructor.
     * @property {module:model/RaceEnum}
     */
    RaceEnum,

    /**
     * The RejectReason model constructor.
     * @property {module:model/RejectReason}
     */
    RejectReason,

    /**
     * The RemoteData model constructor.
     * @property {module:model/RemoteData}
     */
    RemoteData,

    /**
     * The RemoteResponse model constructor.
     * @property {module:model/RemoteResponse}
     */
    RemoteResponse,

    /**
     * The RemoteUser model constructor.
     * @property {module:model/RemoteUser}
     */
    RemoteUser,

    /**
     * The ScheduledInterview model constructor.
     * @property {module:model/ScheduledInterview}
     */
    ScheduledInterview,

    /**
     * The Scorecard model constructor.
     * @property {module:model/Scorecard}
     */
    Scorecard,

    /**
     * The Status007Enum model constructor.
     * @property {module:model/Status007Enum}
     */
    Status007Enum,

    /**
     * The Status757Enum model constructor.
     * @property {module:model/Status757Enum}
     */
    Status757Enum,

    /**
     * The StatusA9fEnum model constructor.
     * @property {module:model/StatusA9fEnum}
     */
    StatusA9fEnum,

    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag,

    /**
     * The Url model constructor.
     * @property {module:model/Url}
     */
    Url,

    /**
     * The UrlTypeEnum model constructor.
     * @property {module:model/UrlTypeEnum}
     */
    UrlTypeEnum,

    /**
     * The VeteranStatusEnum model constructor.
     * @property {module:model/VeteranStatusEnum}
     */
    VeteranStatusEnum,

    /**
     * The VisibilityEnum model constructor.
     * @property {module:model/VisibilityEnum}
     */
    VisibilityEnum,

    /**
    * The AccountTokenApi service constructor.
    * @property {module:api/AccountTokenApi}
    */
    AccountTokenApi,

    /**
    * The ActivitiesApi service constructor.
    * @property {module:api/ActivitiesApi}
    */
    ActivitiesApi,

    /**
    * The ApplicationsApi service constructor.
    * @property {module:api/ApplicationsApi}
    */
    ApplicationsApi,

    /**
    * The AttachmentsApi service constructor.
    * @property {module:api/AttachmentsApi}
    */
    AttachmentsApi,

    /**
    * The AvailableActionsApi service constructor.
    * @property {module:api/AvailableActionsApi}
    */
    AvailableActionsApi,

    /**
    * The CandidatesApi service constructor.
    * @property {module:api/CandidatesApi}
    */
    CandidatesApi,

    /**
    * The DepartmentsApi service constructor.
    * @property {module:api/DepartmentsApi}
    */
    DepartmentsApi,

    /**
    * The EeocsApi service constructor.
    * @property {module:api/EeocsApi}
    */
    EeocsApi,

    /**
    * The InterviewsApi service constructor.
    * @property {module:api/InterviewsApi}
    */
    InterviewsApi,

    /**
    * The JobInterviewStagesApi service constructor.
    * @property {module:api/JobInterviewStagesApi}
    */
    JobInterviewStagesApi,

    /**
    * The JobsApi service constructor.
    * @property {module:api/JobsApi}
    */
    JobsApi,

    /**
    * The LinkTokenApi service constructor.
    * @property {module:api/LinkTokenApi}
    */
    LinkTokenApi,

    /**
    * The OffersApi service constructor.
    * @property {module:api/OffersApi}
    */
    OffersApi,

    /**
    * The OfficesApi service constructor.
    * @property {module:api/OfficesApi}
    */
    OfficesApi,

    /**
    * The PassthroughApi service constructor.
    * @property {module:api/PassthroughApi}
    */
    PassthroughApi,

    /**
    * The RejectReasonsApi service constructor.
    * @property {module:api/RejectReasonsApi}
    */
    RejectReasonsApi,

    /**
    * The ScorecardsApi service constructor.
    * @property {module:api/ScorecardsApi}
    */
    ScorecardsApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
